### ISSUE TITLE
你的BCM94360CS2网卡是怎么装进m930q的

### ISSUE THREAD

**Issue by herotiga** [hackintosh-club/ThinkCentre-M930q#1]
你的BCM94360CS2网卡是怎么装进m930q的，我的m930q网卡插槽距离机箱不够。

还有一个，昨天用你的efi装ventura的时候，进入安装界面后就卡住了，一直卡在白苹果界面，进度条就走了一点点然后就不动了

**Comment by mrasong** [comment]
反向转接卡，用EFI的时候需要自行添加三码，默认是空的

**Comment by herotiga** [comment]
三码哪里来的，写进哪个文件

**Comment by herotiga** [comment]
谢谢，我知道了，EFI没注入三码，怪不得我装了两次都卡白苹果

**Comment by herotiga** [comment]
我写入了三码 替换了efi 然后安装界面依然是卡在了白苹果界面

**Comment by mrasong** [comment]
> 我写入了三码 替换了efi 然后安装界面依然是卡在了白苹果界面

已经开始安装了？还是还未开始安装？
可以开 -v 看看日志

**Comment by chyhero** [comment]
我用您的efi也是卡了。
我是930q ，10400。

另外，-v在哪里设置，看不到码
