### ISSUE TITLE
进入安装界面时卡白苹果

### ISSUE THREAD

**Issue by huanghaolun** [hackintosh-club/ThinkCentre-M930q#2]
![IMG_20230401_000327](https://user-images.githubusercontent.com/47547712/229171965-f786008a-9df0-4fee-8236-bb93e58a4cd4.jpg)

**Comment by mrasong** [comment]
替换三码了吗？
硬件信息发一下

**Comment by huanghaolun** [comment]
已写入三码

CPU： i7 10700
显卡：UHD630
内存：DDR4 8G
硬盘：西数 SN570 1T
板载网卡：Intel I219
无线网卡：BCM94360CS2

**Comment by mrasong** [comment]
BIOS按要求设置了吗？
CFG解锁没有？

**Comment by huanghaolun** [comment]
Serial Port1 Address: Disabled 这项没在BIOS找到，其余都按要求设置了。
CFG解锁，搜索了一下没找到教程，能否指点一下。

**Comment by mrasong** [comment]
EFI引导界面，按空格，有个CFGlock，进行按提示处理即可

**Comment by huanghaolun** [comment]
解锁CFG了，但还是一样卡住

**Comment by mrasong** [comment]
重置下NVRAM？
